-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, SUBSTRING(DATE_OF_BIRTH,1,10) DATE_OF_BIRTH from MEMBER_PROFILE
where MONTH(DATE_OF_BIRTH) = '3' and TLNO is NOT NULL and GENDER = 'W'
order by MEMBER_ID