-- 코드를 작성해주세요

select 
YEAR(DATE(ed.DIFFERENTIATION_DATE)) as YEAR,
ed2.v - ed.SIZE_OF_COLONY as YEAR_DEV,
ed.ID
from ECOLI_DATA ed
left join (
    SELECT DIFFERENTIATION_DATE, MAX(SIZE_OF_COLONY) as v FROM ECOLI_DATA
    where SIZE_OF_COLONY
    group by YEAR(DATE(DIFFERENTIATION_DATE)) 
) ed2
on YEAR(DATE(ed.DIFFERENTIATION_DATE)) = YEAR(DATE(ed2.DIFFERENTIATION_DATE))
order by YEAR asc, YEAR_DEV asc
# SELECT MAX(ed.SIZE_OF_COLONY) FROM ECOLI_DATA ed
# where ed.SIZE_OF_COLONY
# group by YEAR(DATE(ed.DIFFERENTIATION_DATE))