SELECT
    SUM(hg.SCORE) AS SCORE,
    he.EMP_NO,
    he.EMP_NAME,
    he.POSITION,
    he.EMAIL
FROM HR_EMPLOYEES he
LEFT JOIN HR_GRADE hg
    ON he.EMP_NO = hg.EMP_NO
where hg.YEAR = 2022
GROUP BY he.EMP_NO, hg.YEAR
ORDER BY SCORE DESC
LIMIT 1;