-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, CAST(r.CREATED_DATE AS CHAR) from USED_GOODS_BOARD b
inner join USED_GOODS_REPLY r
on b.BOARD_ID = r.BOARD_ID
WHERE YEAR(b.CREATED_DATE)  = 2022
  AND MONTH(b.CREATED_DATE) = 10
order by r.CREATED_DATE, b.TITLE
